### ISSUE TITLE
PDF not working

### ISSUE THREAD

**Issue by 7aklhz** [A9T9/OCR.Space-OCR-API-Code-Snippets#2]
Hi, 

I'm having an issue with PDF files. I get "Not a valid base64 image. The accepted base64 image format is 'data:image/<content_type>;base64,<base64_image_content>". The strange thing is that it says it requires "data:image/" but PDFs are "application/pdf". What is the solution ? 

Cheers, 

K.

**Comment by A9T9** [comment]
Hi,

We currently do not support BASE64 upload method for PDFs. Please use the `file ` or `url `method to upload PDFs.

If you are user of the PRO PDF plan and need base64-support for PDFs, please let us know. If required, we are able to add support for it on short notice. There are no extra costs for this.

**Comment by A9T9** [comment]
Base64 PDF are supported now.
