### ISSUE TITLE
Timing out

### ISSUE THREAD

**Issue by DanielSmith1239** [A9T9/OCR.Space-OCR-API-Code-Snippets#3]
After updating your code to swift 4, the request times out. please see code below:
`   

    static func getImageText(_ imageData: Data, completion: (String) -> ())
    {
        let url = URL(string: "https://api.ocr.space/parse/image")!
        let boundary: String = "randomString"
        let session = URLSession.shared
 
        let parametersDictionary = ["4159879d4788957": "apikey", "True": "isOverlayRequired",  "eng": "language"]

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.addValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
        let data: Data = createBodyWithBoundary(boundary, parameters: parametersDictionary as [NSObject : AnyObject], imageData: imageData, filename: "yourImage.jpg")
        request.httpBody = data
        
        
        let task = session.dataTask(with: request)
        { data, response, error in
            guard let pageData = data else
            {
                print("error getting ocr: \(error)")
                return
            }
            do
            {
                try print(JSONSerialization.jsonObject(with: pageData, options: .allowFragments))
            }
            catch
            {
                print("json error: \(error)")
            }
        }
        task.resume()
    }
    
    private static func createBodyWithBoundary(_ boundary: String, parameters: [NSObject : AnyObject], imageData data: Data, filename: String) -> Data
    {
        var body: NSMutableData = NSMutableData()
        
        body.append("--\(boundary)\r\n".data(using: .utf8)!)
        body.append("Content-Disposition: form-data; name=\"\("file")\"; filename=\"\(filename)\"\r\n".data(using: .utf8)!)
        body.append("Content-Type: image/jpeg\r\n\r\n".data(using: .utf8)!)
        body.append(data)
    
            
        for key in parameters.keys
        {
            body.append("--\(boundary)\r\n".data(using: .utf8)!)
            body.append("Content-Disposition: form-data; name=\"\(key)\"\r\n\r\n".data(using: .utf8)!)
            body.append("\(parameters[key])\r\n".data(using: .utf8)!)
        }
        
        body.append("--\(boundary)--\r\n".data(using: .utf8)!)
        return body as Data
    }`

**Comment by IshuRocks** [comment]
Use this one


func callOCRSpace(image : UIImage) {
        
   
        // Create URL request
        let url = URL(string: "https://api.ocr.space/Parse/Image")
        var request = URLRequest(url: url!)
        request.httpMethod = "POST"
        
        let boundary = "randomString"
        request.addValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
        
        let session = URLSession.shared
        
        // Image file and parameters
        let imageData = image.jpegData(compressionQuality: 0.6)
        let parametersDictionary = [
            "apikey" : "4159879d4788957",
            "isOverlayRequired" : "True",
            "language" : "eng"
        ]
        
        // Create multipart form body
        let data: Data? = createBody(withBoundary: boundary, parameters: parametersDictionary, imageData: imageData, filename: "yourImage.jpg")
        
        request.httpBody = data
        
        // Start data session
        
        var dataTask: URLSessionDataTask? = nil
        
        dataTask = session.dataTask(with: request, completionHandler: { data, response, error in
            
            var dictonary:NSDictionary?
            do {
                dictonary = try JSONSerialization.jsonObject(with: data!, options: .allowFragments) as? NSDictionary
                if let myDictionary = dictonary
                {
                     DispatchQueue.main.async {
                        self.activityIndicator.stopAnimating()
                        
                        let textArray = NSMutableArray()
                        textArray.addObjects(from: myDictionary["ParsedResults"] as! [Any])
                        
                        let textDict = textArray.object(at: 0) as! NSDictionary
                        self.txtImageText.text = "\(textDict.value(forKey: "ParsedText") ?? "")"
                        
                        print(textArray)
                    }
                    
                    print(myDictionary)
                }
                
            } catch let error as NSError {
                
                DispatchQueue.main.async {
                    print(error)
                    self.activityIndicator.stopAnimating()
                }
            }
            
           
        })
        
        dataTask?.resume()
        
    }

    func createBody(withBoundary boundary: String?, parameters: [AnyHashable : Any]?, imageData data: Data?, filename: String?) -> Data? {
        var body = Data()
        
        if data != nil {
            if let data = "--\(boundary ?? "")\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = "Content-Disposition: form-data; name=\"\("file")\"; filename=\"\(filename ?? "")\"\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = "Content-Type: image/jpeg\r\n\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = data {
                body.append(data)
            }
            if let data = "\r\n".data(using: .utf8) {
                body.append(data)
            }
        }
        
        for key in (parameters?.keys)! {
            if let data = "--\(boundary ?? "")\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = "Content-Disposition: form-data; name=\"\(key)\"\r\n\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = "\(parameters?[key] ?? "")\r\n".data(using: .utf8) {
                body.append(data)
            
        }
        
        if let data = "--\(boundary ?? "")--\r\n".data(using: .utf8) {
            body.append(data)
        }
     }
        
        return body
    }

**Comment by IshuRocks** [comment]
func callOCRSpace(image : UIImage) {
        
        
        // Create URL request
        let url = URL(string: "https://api.ocr.space/Parse/Image")
        var request = URLRequest(url: url!)
        request.httpMethod = "POST"
        
        let boundary = "randomString"
        request.addValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
        
        let session = URLSession.shared
        
        // Image file and parameters
        let imageData = image.jpegData(compressionQuality: 0.6)
        let parametersDictionary = [
            "apikey" : "4159879d4788957",
            "isOverlayRequired" : "True",
            "language" : "eng"
        ]
        
        // Create multipart form body
        let data: Data? = createBody(withBoundary: boundary, parameters: parametersDictionary, imageData: imageData, filename: "yourImage.jpg")
        
        request.httpBody = data
        
        // Start data session
        
        var dataTask: URLSessionDataTask? = nil
        
        dataTask = session.dataTask(with: request, completionHandler: { data, response, error in
            
            var dictonary:NSDictionary?
            do {
                dictonary = try JSONSerialization.jsonObject(with: data!, options: .allowFragments) as? NSDictionary
                if let myDictionary = dictonary
                {
                     DispatchQueue.main.async {
                        self.activityIndicator.stopAnimating()
                        
                        let textArray = NSMutableArray()
                        textArray.addObjects(from: myDictionary["ParsedResults"] as! [Any])
                        
                        let textDict = textArray.object(at: 0) as! NSDictionary
                        self.txtImageText.text = "\(textDict.value(forKey: "ParsedText") ?? "")"
                        
                        print(textArray)
                    }
                    
                    print(myDictionary)
                }
                
            } catch let error as NSError {
                
                DispatchQueue.main.async {
                    print(error)
                    self.activityIndicator.stopAnimating()
                }
            }
            
           
        })
        
        dataTask?.resume()
        
    }

    func createBody(withBoundary boundary: String?, parameters: [AnyHashable : Any]?, imageData data: Data?, filename: String?) -> Data? {
        var body = Data()
        
        if data != nil {
            if let data = "--\(boundary ?? "")\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = "Content-Disposition: form-data; name=\"\("file")\"; filename=\"\(filename ?? "")\"\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = "Content-Type: image/jpeg\r\n\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = data {
                body.append(data)
            }
            if let data = "\r\n".data(using: .utf8) {
                body.append(data)
            }
        }
        
        for key in (parameters?.keys)! {
            if let data = "--\(boundary ?? "")\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = "Content-Disposition: form-data; name=\"\(key)\"\r\n\r\n".data(using: .utf8) {
                body.append(data)
            }
            if let data = "\(parameters?[key] ?? "")\r\n".data(using: .utf8) {
                body.append(data)
            
        }
        
        if let data = "--\(boundary ?? "")--\r\n".data(using: .utf8) {
            body.append(data)
        }
     }
        
        return body
    }
