### ISSUE TITLE
[SWIFT] Does anybody test this?

### ISSUE THREAD

**Issue by miff** [A9T9/OCR.Space-OCR-API-Code-Snippets#4]
Can someone confirm that is ever worked? Thanks

**Comment by A9T9** [comment]
We received this snippet from an OCR API user who said it worked for him, but we (a9t9) have not tested it ourself. We have no Swift knowledge in-house. So if someone can help out, that will be great.

**Comment by miff** [comment]
Ok, thanks for response. I will post here my method for swift 4.

**Comment by mubashirhussain** [comment]
@miff Can you please copy your working code in swift4 here?

**Comment by A9T9** [comment]
For support please ask in our [free OCR forum](https://forum.ui.vision/c/ocr-api)
