### ISSUE TITLE
Examples in `curl-ocrapi-base64.bat` fail to execute

### ISSUE THREAD

**Issue by kostasx** [A9T9/OCR.Space-OCR-API-Code-Snippets#5]
When the command is pasted on the terminal the following error is returned:

{"ParsedResults":null,"OCRExitCode":3,"IsErroredOnProcessing":true,"ErrorMessage":["Not a valid base64 image. The accepted base64 image format is 'data:image/<content_type>;base64,<base64_image_content>'."],"ErrorDetails":"Not a valid base64 image. The accepted base64 image format is 'data:image/<content_type>;base64,<base64_image_content>'.","ProcessingTimeInMilliseconds":"1","SearchablePDFURL":null}

**Comment by amitbha** [comment]
Same error for the demo.

**Comment by A9T9** [comment]
Works in my test:

![batch ocr api](https://user-images.githubusercontent.com/9657938/83311503-ba2de300-a20f-11ea-9b08-1d2c0882074d.jpg)

**Comment by kostasx** [comment]
Thanks for the feedback @A9T9. It's being a long time since I last used the code, so I can't really give back a confirmation. You can close this Issue for the time being. If @amitbha can confirm that this either works or produces the same error, you can re-open the issue and investigate the matter further.
