### ISSUE TITLE
Error index.php "Sorry, there was an error uploading your file."

### ISSUE THREAD

**Issue by mikroobdj** [A9T9/OCR.Space-OCR-API-Code-Snippets#6]
Hi,
PHP, I am not able to see the result in index.php , this is what i am done before submit:

1. I just download the "PHP Demo Web App" and put the folder to the server.
2. Change the folder name from "PHP Demo Web App"  to "demo".
3. Change apikey from "helloworld" to my valid apiKey at line 39, File Processing.php.
4. Open index.php in my browser.
5. Choose file and then click on upload button.

but show:
Error "Sorry, there was an error uploading your file."
Any help Please.
Thank you.

![image](https://user-images.githubusercontent.com/27820041/43793821-44f72816-9a42-11e8-9a9f-fa45eaa20960.png)
![image](https://user-images.githubusercontent.com/27820041/43793877-617af5ee-9a42-11e8-8715-46717994ecfc.png)
File Processing.php : 
![image](https://user-images.githubusercontent.com/27820041/43793981-aa4b332e-9a42-11e8-91de-fe5d73d7c6f2.png)

**Comment by Andy22-wp** [comment]
Hi, have you solved? I have the same problem. Thanks

**Comment by Andy22-wp** [comment]
Ok, i understand, you must create in the root the uploads/ directory, bye.
