### ISSUE TITLE
Adding Kurdish Sorani Lang

### ISSUE THREAD

**Issue by hamashexler** [A9T9/OCR.Space-OCR-API-Code-Snippets#7]
It's almost same as Arabic, but we only have few letters difference Can you add it ? or at least give me files so I will add it I been looking for the files but I can't figure out where they are.

**Comment by A9T9** [comment]
Added to todo list.

**Comment by Bahroz-Barzani** [comment]
@A9T9 What did you do, bro?
Did you add (kurdish - sorani) letters?
It's almost same as Arabic, except these letters: ڕ ژ گ ڤ ۆ پ چ ێ
