### ISSUE TITLE
add post params

### ISSUE THREAD

**Issue by pws2016** [A9T9/OCR.Space-OCR-API-Code-Snippets#9]
Hello,
i'm using your php sscript but how i can add post params? as isOverlayRequired=true

**Comment by A9T9** [comment]
Please see:

- https://forum.ui.vision/t/ocr-engine2-within-php/4897
- https://forum.ui.vision/t/how-to-set-ocr-language-in-the-example-php-script/367
- https://forum.ui.vision/t/ocr-free-api-whit-php/3619
- https://forum.ui.vision/t/i-am-getting-different-result-in-online-demo-and-provided-php-code/1483
